language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_FRAMEWORK_SCHEME="Navajo iOS"
  - OSX_FRAMEWORK_SCHEME="Navajo OSX"
  - IOS_SDK=iphonesimulator10.0
  - OSX_SDK=macosx10.12
  matrix:
    - DESTINATION="OS=9.0,name=iPhone 6 Plus"   SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  POD_LINT="YES"
    - DESTINATION="OS=9.1,name=iPhone 6S"       SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  POD_LINT="NO"
    - DESTINATION="OS=9.2,name=iPhone 6S Plus"  SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  POD_LINT="NO"
    - DESTINATION="OS=9.3,name=iPhone 6S Plus"  SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  POD_LINT="NO"
    - DESTINATION="OS=10.0,name=iPhone 7"  SCHEME="$IOS_FRAMEWORK_SCHEME"  SDK="$IOS_SDK"  POD_LINT="NO"
    - DESTINATION="arch=x86_64"                 SCHEME="$OSX_FRAMEWORK_SCHEME"  SDK="$OSX_SDK"  POD_LINT="NO"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build and run tests in Debug and Release
  - xcodebuild -project Navajo.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
  - xcodebuild -project Navajo.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO test | xcpretty -c;

  # Run pod lib lint quick if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --quick;
    fi
